<?php
/** @var ModernPage $startMasonry */

use App\Database\ModernPage;

$startMasonry = $this->ModernPage('startpage');
?>
<?php
$this->layout('theme::layout') ?>
<?php
$this->start('maincontent') ?>
<main class="jinya-startpage">
    <?php
    foreach ($startMasonry->getSections() as $section): ?>
        <?php
        if ($section->html !== null): ?>
            <?= $section->html ?>
        <?php
        elseif ($section->fileId !== null): ?>
            <?php
            $file = $section->getFile() ?>
            <a class="jinya-startpage__item" href="<?= $this->e($section->target) ?>">
                <img src="<?= $this->e($file->path) ?>" alt="<?= $this->e($file->name) ?>">
            </a>
        <?php
        endif ?>
    <?php
    endforeach ?>
</main>
<?php
$this->stop() ?>
