version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.6.0
  - dependency-name: phpmailer/phpmailer
    versions:
    - 6.3.0
    - 6.4.0
  - dependency-name: fakerphp/faker
    versions:
    - 1.14.0
    - 1.14.1
  - dependency-name: php-di/php-di
    versions:
    - 6.3.1
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
  - dependency-name: nyholm/psr7
    versions:
    - 1.4.0
- package-ecosystem: npm
  directory: "/designer"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.1
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: svelte
    versions:
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
    - 3.36.0
    - 3.37.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
    - 11.2.0
    - 11.2.1
  - dependency-name: svelte-i18n
    versions:
    - 3.3.2
    - 3.3.4
    - 3.3.5
    - 3.3.6
    - 3.3.7
    - 3.3.9
  - dependency-name: apexcharts
    versions:
    - 3.25.0
    - 3.26.0
  - dependency-name: monaco-editor
    versions:
    - 0.23.0
  - dependency-name: eslint-plugin-svelte3
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: rollup-plugin-copy
    versions:
    - 3.4.0
  - dependency-name: ua-parser-js
    versions:
    - 0.7.24
  - dependency-name: tinymce
    versions:
    - 5.7.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
