workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

include:
  - /ci/gitlab/designer.yml
  - /ci/gitlab/docker.yml
  - /ci/gitlab/global-variables.yml
  - /ci/gitlab/installer.yml
  - /ci/gitlab/packages.yml
  - /ci/gitlab/php-lint.yml
  - /ci/gitlab/stages.yml
  - /ci/gitlab/templates.yml
  - /ci/gitlab/tests.yml
