include:
  - /ci/includes/deployment.yml
  - /ci/includes/designer.yml
  - /ci/includes/global-variables.yml
  - /ci/includes/installer.yml
  - /ci/includes/php-lint.yml
  - /ci/includes/stages.yml
  - /ci/includes/templates.yml
  - /ci/includes/tests.yml
