title: Jinya CMS
description: A content managment system, made by artists for artists
remote_theme: Jinya-CMS/just-the-docs
logo: /public/static/favicon-512x512.png
aux_links:
  "Jinya CMS on Github":
    - "https://github.com/Jinya-CMS/jinya-cms"
aux_links_new_tab: true
gh_edit_repository: "https://github.com/Jinya-CMS/jinya-cms"
