version: '3.9'

volumes:
  logs:
    driver: local

services:
  jinya-mysql-database:
    image: library/mariadb:11
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3336:3306
  jinya-mysql-additional-database:
    image: library/mariadb:11
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3356:3306
  jinya-mysql-test-database:
    image: library/mariadb:11
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3346:3306
  jinya-mailer:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "true"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    ports:
      - 8525:8025
      - 1525:1025
  jinya-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - jinya-mailer
      - jinya-mysql-database
      - jinya-mysql-test-database
      - jinya-tidb

  jinya-tidb:
    image: pingcap/tidb:v7.3.0
    ports:
      - "4000:4000"
      - "10080:10080"
    command:
      - --store=unistore
      - --path=""
      - --log-file=/logs/tidb.log
      - --advertise-address=jinya-tidb
    restart: on-failure