FROM quay.imanuel.dev/dockerhub/library---php:8.0-apache

COPY ./docker/conf/memory-limit.ini /usr/local/etc/php/conf.d/memory-limit.ini
COPY ./docker/conf/opcache.ini /usr/local/etc/php/conf.d/opcache-recommended.ini
COPY ./docker/entrypoint.sh /entrypoint.sh

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN apt-get update
RUN apt-get install libzip-dev -y
RUN docker-php-ext-install pdo pdo_mysql zip opcache
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN pecl install apcu && docker-php-ext-enable apcu
RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini && echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini && echo "xdebug.discover_client_host=yes" >> /usr/local/etc/php/conf.d/xdebug.ini
RUN a2enmod rewrite
RUN a2enmod headers
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

CMD ["apache2-foreground"]
EXPOSE 80