volumes:
  logs:
    driver: local

services:
  jinya-mysql-database:
    image: library/mysql:8
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 4336:3306
  jinya-mariadb-database:
    image: library/mariadb:11
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3336:3306
  jinya-mariadb-additional-database:
    image: library/mariadb:11
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3356:3306
  jinya-mariadb-test-database:
    image: library/mariadb:11
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3346:3306
  jinya-mailer:
    image: axllent/mailpit:latest
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 'true'
      MP_SMTP_AUTH_ALLOW_INSECURE: 'true'
    ports:
      - 8525:8025
      - 1525:1025
  jinya-imaginary:
    image: h2non/imaginary:latest
  jinya-backend:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - jinya-mailer
      - jinya-mysql-database
      - jinya-mariadb-database
      - jinya-mariadb-test-database
      - jinya-mariadb-additional-database
      - jinya-imaginary
