version: '3.9'

volumes:
  logs:
    driver: local

services:
  jinya-mysql-database:
    image: library/mysql:8
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3336:3306
  jinya-mysql-test-database:
    image: library/mysql:8
    environment:
      MYSQL_DATABASE: jinya
      MYSQL_PASSWORD: jinya
      MYSQL_ROOT_PASSWORD: jinya
      MYSQL_USER: jinya
    ports:
      - 3346:3306
  jinya-mailhog:
    image: mailhog/mailhog
    ports:
      - 8525:8025
      - 1525:1025
  jinya-webgrind:
    image: jokkedk/webgrind:latest
    ports:
      - 8088:80
    volumes:
      - ./profile:/tmp
  jinya-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - jinya-mailhog
      - jinya-mysql-database
      - jinya-mysql-test-database