parameters:
  - name: id
    schema:
      type: integer
    in: path
    required: true
get:
  summary: Get the configuration structure
  tags:
    - themes
  responses:
    '200':
      description: The theme configuration structure
      content:
        application/json:
          schema:
            $ref: ../components/schemas/theme-configuration-structure.yaml
    '401':
      description: Api key missing
      content:
        application/json:
          schema:
            $ref: ../components/schemas/exception.yaml
    '403':
      description: Invalid api key
      content:
        application/json:
          schema:
            $ref: ../components/schemas/exception.yaml
    '404':
      description: Theme not found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/exception.yaml
  operationId: get_theme_configuration_structure
  description: Gets the configuration structure for the given theme
  security:
    - header-auth: []
    - cookie-auth: []
