<?php
/**
 * @var $this Template
 * @var $artistName string
 * @var $remoteAddress string
 * @var $location array
 * @var $browser string
 * @var $platform string
 */

use League\Plates\Template\Template;

?>
<html lang="en">
<body>
<p>
    Hello <?= $this->e($artistName) ?><br/><br/>
    there was a new successful login for your account.
</p>
<p>
    The login was from the IP address <?= $this->e($remoteAddress) ?>.
    <?php
    if (array_key_exists('city', $location) && !empty($location['city'])): ?>
        Which is located at, <?= $this->e($location['city']) ?>, <?= $this->e($location['region_name']) ?> in <?= $this->e(
            $location['country_name']
        ) ?>.
    <?php
    endif ?>
</p>
<?php
if (!empty($browser)): ?>
    <p>
        The browser used was <?= $this->e($browser) ?> on <?= $this->e($platform) ?>
    </p>
<?php
endif ?>
<p>
    Greetings,<br/>
    Your Jinya Team
</p>
</body>
</html>
