<?php
/**
 * @var $this Template
 * @var $artistName string
 * @var $remoteAddress string
 * @var $location array
 * @var $browser string
 * @var $platform string
 */

use League\Plates\Template\Template; ?>
Hello <?= $this->e($artistName) ?>

there was a new successful login for your account.

The login was from the IP address <?= $this->e($remoteAddress) ?>.
<?php
if (array_key_exists('city', $location) && !empty($location['city'])): ?>
    Which is located at, <?= $this->e($location['city']) ?>, <?= $this->e($location['regionName']) ?> in <?= $this->e(
        $location['country']
    ) ?>.
<?php
endif ?>
<?php
if (!empty($browser)): ?>
    The browser used was <?= $this->e($browser) ?> on <?= $this->e($platform) ?>
<?php
endif ?>

Greetings,
Your Jinya Team
