<?php
/**
 * @var $this Template
 * @var $artistName string
 * @var $remoteAddress string
 * @var $location array
 * @var $browser string
 * @var $platform string
 * @var $subject string
 */

use Jinya\Plates\Template\Template;

?>
<?php
$this->layout('mailing::layout', ['subject' => $subject]);
$this->start('maincontent') ?>
<p>
    <?= $this->e($this->translate('greeting', $artistName)) ?><br /><br />
    <?= $this->e($this->translate('new_device_greeting_line')) ?>
</p>
<p>
    <?= $this->e($this->translate('new_device_ip_line', $remoteAddress)) ?>
    <?= $this->e($this->translate('new_device_location_line', $location['city'], $location['country'])) ?>
</p>
<?php
if (!empty($browser)): ?>
    <p>
        <?= $this->e($this->translate('new_device_browser_line', $browser)) ?>
    </p>
<?php
endif ?>
<?php
$this->stop(); ?>
