<?php
/**
 * @var $this Template
 * @var $artistName string
 * @var $remoteAddress string
 * @var $location array
 * @var $browser string
 * @var $platform string
 */

use Jinya\Plates\Template\Template;

?>
<?= $this->e($this->translate('greeting', $artistName)) ?>

<?= $this->e($this->translate('new_device_greeting_line')) ?>

<?= $this->e($this->translate('new_device_ip_line', $remoteAddress)) ?>

<?php
if ($location['city']): ?>
<?= $this->e($this->translate('new_device_location_line', $location['city'], $location['country'])) ?>
<?php
endif ?>
<?php
if (!empty($browser)): ?>

<?= $this->e($this->translate('new_device_browser_line', $browser)) ?>
<?php
endif; ?>

-- Jinny - Jinya CMS bot

<?= $this->translate('ip_db') ?>
