<?php
/**
 * @var $this Template
 * @var $artistName string
 * @var $twoFactorCode string
 * @var $subject string
 */

use Jinya\Plates\Template\Template;

?>
<?php
$this->layout('mailing::layout', ['subject' => $subject, 'hasIp' => false]);
$this->start('maincontent') ?>
<p>
    <?= $this->e($this->translate('greeting', $artistName)) ?><br /><br />
    <?= $this->e($this->translate('two_factor_code_text_line')) ?>
</p>
<center>
    <code><?= $this->e($twoFactorCode) ?></code>
</center>
<?php
$this->stop(); ?>
