<?php
/**
 * @var $this Template
 * @var $artistName string
 * @var $twoFactorCode string
 */

use Jinya\Plates\Template\Template;

?>
<html lang="en">
<body>
<p>
  Hello <?= $this->e($artistName) ?><br /><br />
  You tried to log in from a new device, please verify with this code that this was actually you.
</p>
<p>
  <code><?= $this->e($twoFactorCode) ?></code>
</p>
<p>
  Greetings,<br />
  Your Jinya Team
</p>
</body>
</html>
