$schema: "https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json"

stages:
  - lint
  - test
  - build-docker
  - deploy-package
  - deploy-docker
  - deploy-pages
