<?php
/** @var MenuItem $item */

/** @var MenuItem $activeMenuItem */

/** @var string $additionalClass */

use Jinya\Cms\Database\MenuItem;

if ($activeMenuItem !== null):
    $activeMenuItem = $this->getActiveMenuItem();
    $activeMenuItemParent = $activeMenuItem->parentId !== null ? $activeMenuItem->getParent() : $activeMenuItem;
    $itemCount = iterator_count($item->getItems());
    $activeMenuItemParentItemCount = iterator_count($activeMenuItemParent->getItems());
else:
    $activeMenuItem = null;
    $activeMenuItemParent = null;
    $itemCount = iterator_count($item->getItems());
    $activeMenuItemParentItemCount = 0;
endif
?>
<li class="jinya-menu__item
    <?= $activeMenuItemParentItemCount > 0 && $item->id !== $activeMenuItemParent->id ? 'is--hidden' : '' ?>
    <?php
if ($this->isChildActiveMenuItem($item)): ?>
        is--current
    <?php
else: ?>
    <?php
    if (isset($activeMenuItem->menuId) && empty($activeMenuItem->menuId)): ?>
        is--hidden
    <?php
    elseif (!empty($activeMenuItem->menuId) && $item !== null && $activeMenuItem->id === $item->id): ?>
        is--current
    <?php
    endif ?>
    <?php
endif ?>
    <?= $itemCount > 0 ? 'has--children' : '' ?>
">
    <?php
    if ($itemCount > 0): ?>
        <span class="jinya-menu__link has--children <?= $item->highlighted ? 'is--highlight' : '' ?>">
            <?= $this->e($item->title) ?>
        </span>
        <?= $this->insert('theme::includes/submenu/submenu', ['item' => $item]) ?>
    <?php
    else: ?>
        <?= $this->insert('theme::includes/menu_link', ['item' => $item, 'class' => 'jinya-menu__link']) ?>
    <?php
    endif ?>
</li>
