<?php
/** @var Theme $theme */

/** @var Menu $menu */

/** @var MenuItem $activeMenuItem */

use Jinya\Cms\Database\Menu;
use Jinya\Cms\Database\MenuItem;
use Jinya\Cms\Database\Theme;

$activeMenuItem = $this->getActiveMenuItem();
$menu = $this->menu('primary');
?>
<header class="jinya-header">
    <?php
    if (isset($menu)): ?>
        <ul class="jinya-menu">
            <?php
            if ($activeMenuItem !== null && $activeMenuItem->parentId !== null): ?>
                <li class="jinya-menu__item has--back-arrow ">
                    <a class="jinya-menu__back-arrow"></a>
                </li>
            <?php
            else: ?>
                <li class="jinya-menu__item has--back-arrow is--hidden">
                    <a class="jinya-menu__back-arrow"></a>
                </li>
            <?php
            endif ?>
            <?php
            foreach ($menu->getItems() as $item): ?>
                <?= $this->insert(
                    'theme::includes/menu/item',
                    [
                                        'item' => $item,
                                        'activeMenuItem' => $activeMenuItem,
                                    ]
                ) ?>
            <?php
            endforeach ?>
        </ul>
    <?php
    endif ?>
    <a class="jinya-brand" href="/"><?= $this->e($menu->name) ?></a>
    <button class="jinya-menu__hamburger">
        <span class="jinya-menu-hamburger__bar"></span>
        <span class="jinya-menu-hamburger__bar"></span>
        <span class="jinya-menu-hamburger__bar"></span>
    </button>
</header>
