<?php
/** @var Template $this */

/** @var MenuItem $item */

use App\Database\MenuItem;
use League\Plates\Template\Template;

$subItems = iterator_to_array($item->getItems());
?>
<li>
  <a href="<?= $item->route ?>"><?= $item->title ?></a>
    <?php
    if (!empty($subItems)): ?>
      <ul>
          <?php
          foreach ($subItems as $subItem): ?>
              <?= $this->fetch('theme::include/menuitem', ['item' => $subItem]) ?>
          <?php
          endforeach ?>
      </ul>
    <?php
    endif ?>
</li>
