<?php

namespace Jinya\Cms\Database;

use Jinya\Cms\Logging\Logger;
use Jinya\Cms\Web\Middleware\AuthorizationMiddleware;
use Jinya\Database\Attributes\Column;
use Jinya\Database\Attributes\Id;
use Jinya\Database\Attributes\Table;
use Jinya\Router\Extensions\Database\Attributes\Create;
use Jinya\Router\Extensions\Database\Attributes\Delete;
use Jinya\Router\Extensions\Database\Attributes\Find;
use Jinya\Router\Extensions\Database\Attributes\Update;

/**
 * This class contains information about the tags of files
 */
#[Table('file_tag')]
#[Find('/api/file-tag', new AuthorizationMiddleware(ROLE_READER))]
#[Create('/api/file-tag', new AuthorizationMiddleware(ROLE_WRITER))]
#[Update('/api/file-tag', new AuthorizationMiddleware(ROLE_WRITER))]
#[Delete('/api/file-tag', new AuthorizationMiddleware(ROLE_WRITER))]
class FileTag extends LoggingEntity
{
    #[Id]
    #[Column(autogenerated: true)]
    public int $id;

    /** @var string The name of the tag */
    #[Column]
    public string $name;

    /** @var string|null The color of the tag */
    #[Column]
    public ?string $color = null;

    /** @var string|null The emoji of the tag */
    #[Column]
    public ?string $emoji = null;

    /**
     * Finds the given tag by name
     *
     * @param string $name
     * @return FileTag|null
     */
    public static function findByName(string $name): ?FileTag
    {
        $loggger = Logger::getLogger();
        $loggger->debug('Get tag by name', ['name' => $name]);

        $query = self::getQueryBuilder()
            ->newSelect()
            ->from(self::getTableName())
            ->cols([
                'id',
                'name',
                'emoji',
                'color'
            ])
            ->where('name = :name', ['name' => $name]);

        /** @var array<string, mixed>[] $data */
        $data = self::executeQuery($query);
        if (empty($data)) {
            return null;
        }

        return self::fromArray($data[0]);
    }

    /**
     * @return array{'name': string, 'color': string|null, 'emoji': string|null}
     */
    public function format(): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'color' => $this->color,
            'emoji' => $this->emoji,
        ];
    }
}
