<?php
/** @var string $version */
/** @var string $newVersion */
?>
<html lang="en">
<head>
    <title>Update Jinya to Version <?= $newVersion ?></title>
    <style>
        :root {
            font-size: 16px;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
            --white: #ffffff;
            --primary: #514B57;
            --primary-light: #7c7285;
            --primary-dark: #151417;
            --invalid-color: #5C0B0B;
            --info-color: #182B70;
        }

        .updater-content {
            display: flex;
            justify-content: center;
        }

        .updater-button {
            float: right;
            border: none;
            border-bottom: 2px solid var(--primary);
            background: var(--primary-light);
            padding: 0.5rem;
            cursor: pointer;
            transition: background 0.3s, box-shadow 0.3s;
            font-size: 1rem;
            outline: none;
            box-sizing: border-box;
            color: var(--white);
        }

        .updater-button:hover,
        .updater-button:focus {
            box-shadow: 0 0.25rem 0.25rem 0 var(--primary);
        }

        .updater-message--error {
            box-shadow: 0 0.25rem 0.25rem 0 var(--invalid-color);
            padding: 1rem;
            color: var(--invalid-color);
            border-top: 4px solid var(--invalid-color);
        }

        .updater-message--info {
            box-shadow: 0 0.25rem 0.25rem 0 var(--info-color);
            padding: 1rem;
            color: var(--info-color);
            border-top: 4px solid var(--info-color);
        }

        .updater-form {
            width: auto;
            background: #eee;
            padding: 2rem;
        }

        .updater-button-bar {
            display: flex;
            justify-content: flex-end;
            margin-top: 2rem;
            gap: 1rem;
        }
    </style>
</head>
<body>
<main class="updater-content">
    <form method="post" class="updater-form">
        <input type="hidden" name="newVersion" value="<?= $newVersion ?>">
        <h1>Update Jinya</h1>
        <?php if (isset($error)): ?>
            <div class="updater-message--error">
                Error updating Jinya to version <?= $newVersion ?>
            </div>
        <?php else: ?>
            <div class="updater-message--info">
                You currently have version <?= $version ?> installed. The update will install version <?= $newVersion ?>
            </div>
        <?php endif ?>
        <div class="updater-button-bar">
            <button type="submit" name="cancel" class="updater-button">Cancel update</button>
            <button type="submit" name="update" class="updater-button">Update Jinya</button>
        </div>
    </form>
</main>
</body>
</html>
