<?php
/** @var BlogPost $post */

use App\Database\BlogPost;
use App\Database\BlogPostSection;
use App\Database\Gallery;
use App\Utils\ImageType;

?>
<div class="jinya-post__post">
    <?php
    /** @var BlogPostSection $section */ ?>
    <?php
    foreach ($post->getSections() as $section): ?>
        <section class="jinya-post__segment <?= $section->fileId !== null ? 'jinya-post__segment--file' : '' ?>">
            <?php
            if ($section->galleryId): ?>
                <?php
                $gallery = $section->getGallery(); ?>
                <?= $this->insert('theme::includes/gallery', [
                    'gallery' => $gallery,
                    'noCaption' => $gallery->orientation === Gallery::ORIENTATION_HORIZONTAL && $gallery->type === Gallery::TYPE_SEQUENCE,
                    'extraClass' => 'jinya-gallery--post',
                ]) ?>
            <?php
            elseif ($section->html): ?>
                <div class="jinya-post__html-segment">
                    <?= $section->html ?>
                </div>
            <?php
            elseif ($section->fileId): ?>
                <?php
                $file = $section->getFile() ?>
                <figure class="jinya-post__img-container">
                    <?php
                    if ($section->link === null): ?>
                        <img class="jinya-post__artwork" src="<?= $this->e($file->path) ?>"
                             alt="<?= $this->e($file->name) ?>" sizes="<?= $this->sizes() ?>"
                             srcset="<?= $this->srcset($file, ImageType::Webp) ?>">
                    <?php
                    else: ?>
                        <a href="<?= $section->link ?>">
                            <img class="jinya-post__artwork" src="<?= $this->e($file->path) ?>"
                                 alt="<?= $this->e($file->name) ?>" sizes="<?= $this->sizes() ?>"
                                 srcset="<?= $this->srcset($file, ImageType::Webp) ?>">
                        </a>
                    <?php
                    endif ?>
                    <figcaption class="jinya-post__img-caption"><?= $file->name ?></figcaption>
                </figure>
            <?php
            endif ?>
        </section>
    <?php
    endforeach ?>
</div>
