<?php

/** @var BlogPost $post */

use Jinya\Cms\Database\BlogPost;
use Jinya\Cms\Database\BlogPostSection;
use Jinya\Cms\Database\File;
use Jinya\Cms\Database\Gallery;
use Jinya\Cms\Database\GalleryFilePosition;

$headerImage = $post->getHeaderImage();
$data = [
    'title' => $post->title,
    'createdAt' => $post->createdAt->format(DATE_ATOM),
    'headerImage' => $headerImage ? [
        'name' => $headerImage->name,
        'path' => $headerImage->path,
    ] : null,
    'segments' => array_map(static function (BlogPostSection $section): array {
        $data = [
            'position' => $section->position,
        ];
        if (isset($section->galleryId)) {
            $gallery = Gallery::findById($section->galleryId);
            $data['gallery'] = [
                'name' => $gallery?->name,
                'description' => $gallery?->description,
                'type' => $gallery?->type,
                'orientation' => $gallery?->orientation,
                'images' => array_map(static function (GalleryFilePosition $file): array {
                    $f = $file->getFile();
                    return [
                        'position' => $file->position,
                        'path' => $f->path,
                        'name' => $f->name,
                        'type' => $f->type,
                    ];
                }, iterator_to_array($gallery->getFiles())),
            ];
        } elseif (isset($section->fileId)) {
            $file = File::findById($section->fileId);
            $data['file'] = [
                'name' => $file?->name,
                'type' => $file?->type,
                'path' => $file?->path,
            ];
            $data['link'] = $section->link;
        } else {
            $data['html'] = $section->html;
        }

        return $data;
    }, iterator_to_array($post->getSections())),
];

echo json_encode($data, JSON_THROW_ON_ERROR);
