<?php

/** @var SegmentPage $startMasonry */

use App\Database\File;
use App\Database\Gallery;
use App\Database\Segment;
use App\Database\SegmentPage;

$startMasonry = $this->segmentPage('startpage');
$segments = iterator_to_array($startMasonry->getSegments());
$filteredSegments = array_filter($segments, static fn(Segment $segment) => $segment->galleryId === null);

$data = array_map(static function (Segment $segment) {
    $data = [
        'position' => $segment->position,
    ];
    if (isset($segment->galleryId)) {
        $gallery = Gallery::findById($segment->galleryId);
        $data['gallery'] = [
            'name' => $gallery?->name,
            'description' => $gallery?->description,
            'type' => $gallery?->type,
            'orientation' => $gallery?->orientation,
        ];
    } elseif (isset($segment->fileId)) {
        $file = File::findById($segment->fileId);
        $data['file'] = [
            'name' => $file?->name,
            'type' => $file?->type,
            'path' => $file?->path,
        ];
        $data['action'] = $segment->action;
        $data['script'] = $segment->script;
        $data['target'] = $segment->target;
    } else {
        $data['html'] = $segment->html;
    }

    return $data;
}, $filteredSegments);

echo json_encode(array_values($data), JSON_THROW_ON_ERROR);