<?php

/** @var ModernPage $startMasonry */

use Jinya\Cms\Database\File;
use Jinya\Cms\Database\Gallery;
use Jinya\Cms\Database\ModernPageSection;
use Jinya\Cms\Database\ModernPage;

$startMasonry = $this->ModernPage('startpage');
$sections = iterator_to_array($startMasonry->getSections());
$filteredSegments = array_filter($sections, static fn (ModernPageSection $section) => $section->galleryId === null);

$data = array_map(static function (ModernPageSection $section) {
    $data = [
        'position' => $section->position,
    ];
    if (isset($section->galleryId)) {
        $gallery = Gallery::findById($section->galleryId);
        $data['gallery'] = [
            'name' => $gallery?->name,
            'description' => $gallery?->description,
            'type' => $gallery?->type,
            'orientation' => $gallery?->orientation,
        ];
    } elseif (isset($section->fileId)) {
        $file = File::findById($section->fileId);
        $data['file'] = [
            'name' => $file?->name,
            'type' => $file?->type,
            'path' => $file?->path,
        ];
        $data['action'] = $section->action;
        $data['script'] = $section->script;
        $data['target'] = $section->target;
    } else {
        $data['html'] = $section->html;
    }

    return $data;
}, $filteredSegments);

echo json_encode(array_values($data), JSON_THROW_ON_ERROR);
