<?php
$footerMenu = $this->menu('footer');
$mainMenu = $this->menu('primary');

function formatMenuItem(\App\Database\MenuItem $item): array
{
    $data = [
        'position' => $item->position,
        'highlighted' => $item->highlighted,
        'title' => $item->title,
        'route' => '/' . $item->route,
    ];
    $items = iterator_to_array($item->getItems());
    if (!empty($items)) {
        $data['items'] = array_map('formatMenuItem', $items);
    }

    return $data;
}

$data = [
    'menus' => [
        'primary' => [
            ...$mainMenu->format(),
            'items' => array_map('formatMenuItem', iterator_to_array($mainMenu->getItems())),
        ],
        'footer' => [
            ...$footerMenu->format(),
            'items' => array_map('formatMenuItem', iterator_to_array($footerMenu->getItems())),
        ],
    ]
];

echo json_encode($data, JSON_THROW_ON_ERROR);