<?php

/** @var ModernPage $page */

use App\Database\File;
use App\Database\Gallery;
use App\Database\GalleryFilePosition;
use App\Database\ModernPage;
use App\Database\ModernPageSection;

$data = [
    'title' => $page->name,
    'segments' => array_map(static function (ModernPageSection $section): array {
        $data = [
            'position' => $section->position,
        ];
        if (isset($section->galleryId)) {
            $gallery = Gallery::findById($section->galleryId);
            $data['gallery'] = [
                'name' => $gallery?->name,
                'description' => $gallery?->description,
                'type' => $gallery?->type,
                'orientation' => $gallery?->orientation,
                'images' => array_map(static function (GalleryFilePosition $file): array {
                    $f = $file->getFile();
                    return [
                        'position' => $file->position,
                        'path' => $f->path,
                        'name' => $f->name,
                        'type' => $f->type,
                    ];
                }, iterator_to_array($gallery?->getFiles())),
            ];
        } elseif (isset($section->fileId)) {
            $file = File::findById($section->fileId);
            $data['file'] = [
                'name' => $file?->name,
                'type' => $file?->type,
                'path' => $file?->path,
            ];
            if ($section->action === 'link') {
                $data['link'] = $section->target;
            }
        } else {
            $data['html'] = $section->html;
        }

        return $data;
    }, iterator_to_array($page->getSections())),
];

echo json_encode($data, JSON_THROW_ON_ERROR);
