<?php
/**
 * The file home.phtml gets the variables below passed. In contrast to all other files, the home.phtml gets no variables
 * passed. You should configure your home page content, in the theme.php file and access the assets with the helper
 * methods.
 */
?>
<?php $this->layout('theme::layout') ?>
<?php $this->start('maincontent') ?>
    <main>
        <h1>Welcome to my page</h1>
        <?php // Place your start pages content here. As for every other page you can access your links and then create the content ?>
    </main>
<?php $this->stop() ?>