<?php
/**
 * The file simple-page.phtml gets the variables below passed. The variable $page contains the simple page for this
 * route. When rendering the content, make sure to *not* escape it.
 */

/** @var ClassicPage $page */

use Jinya\Cms\Database\ClassicPage;

?>
<?php
$this->layout('theme::layout', ['title' => $page->title]) ?>
<?php
$this->start('maincontent') ?>
<main>
    <?= $page->content ?>
</main>
<?php
$this->stop() ?>
